language: ruby

script:
  - bundle exec rake test

rvm:
  - 2.2.2
  - 2.3.1

env:
  - DB=mysql2
  - DB=postgresql

before_script:
  - mysql -e 'create database filterrific_demo_test;'
  - psql -c 'create database filterrific_demo_test;' -U postgres

branches:
  except:
    - master
